FROM ubuntu:18.04

RUN apt update && apt install -y curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash
RUN apt install -y nodejs

EXPOSE 5000
ENV REACT_APP_BACKEND_URL=http://localhost:8080

WORKDIR /usr/src/app
COPY ./example-frontend ./

RUN npm install
RUN npm run build
RUN npm install -g serve

RUN useradd -m appuser
RUN chown appuser .
USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]

