FROM golang:1.16-alpine

WORKDIR /usr/src/app
COPY ./example-backend ./

EXPOSE 8080
ENV REQUEST_ORIGIN=http://localhost:5000

RUN go build && \
    adduser -D appuser && \
    chown appuser .
    
USER appuser

CMD ["./server"]
