FROM golang:1.16-alpine AS build-env

WORKDIR /usr/src/app
COPY ./example-backend ./

RUN go build

FROM alpine 

WORKDIR /usr/src/app

COPY --from=build-env /usr/src/app /usr/src/app

EXPOSE 8080
ENV REQUEST_ORIGIN=http://localhost:5000

RUN adduser -D appuser && \
    chown appuser .
    
USER appuser

CMD ["./server"]
